### ISSUE TITLE
Regressions over EA4

### ISSUE THREAD

**Issue by karljohns0n** [CpanelInc/ea-apache2#1]
Hello,

I converted few cPanel servers from EA3 to EA4 to use PHP7 and I found two situations that could be considered as a regression over EA3.

**Mod_ruid2 + ModSecurity**

Those two work fine together on EA3. When selecting ruid2 in EA4, it wont allow ModSecurity, which is an important module to filter all kind of bad requests.

**Symlink race condition patch**

Rack911 and Bluehost patch aren't available in EA4, which can be considered as a security regression over EA3. This patch is a great workaround for those who cannot implement protection using filesystem such as Virtuozzo and OpenVZ containers. The only way you provide in your documentation for this situation would be mod_ruid + jailshell however ruid is not compatible with ModSecurity and that would create so many bind mounts on a filesystem that is already a bind mounts (simfs). It's also considered as experimental. It would be great if you could build an apache package with the Rack911 patch for all customers in this situation. 

Any thoughts?

Karl

**Comment by HoustonDad** [comment]
Hi Karl,

In re: RUID2 & ModSec:
We are working at this time on making ModRUID2 / ITK & ModSec2 work properly together. In EA3, there was a bug with DBM files and per-user MPMs, but EA3 allowed those modules to work together even with that bug. When we were building EA4 initially early last year, I made the call for us to have these two packages conflict, in hopes we'd be able to fix that bug ourselves, however it just hasn't happened, it requires in depth changes to ModSec, which isn't something we're able to do. Right now, we're working on removing this conflict, and getting the stack configured properly depending on the MPMs. 

In regards to the Symlink patch, this patch didn't really do much to stop those attacks. It only caught the TOCTOU condition, but still allowed other vectors of attack. Since this patch didn't do much (and should have only been used as a last resort), we have no plans to offer this patch via EA4. You can pull down our sources, and add this patch yourself, and then distribute those packages to your own farm, but it's not something we're interested in at this time.

**Comment by karljohns0n** [comment]
Hello Jacob,

I indeed had the DBM issue with ruid2 as the user who write in it isn't nobody anymore. The only quick workaround I found yet is an insecure one (nobody with write permission to all). It would be best if the DBM was in memcached/redis but this is on modsec side. Glad to hear you will remove the conflict.

As far as i am concerned, the patch did well on all cPanel servers I saw it installed even if it's not bulletproof. No symlink attack were successfully attempted after the patch was installed and the combo with CSF works fine. With EA4 probably being default in next cPanel release, it would be great to provide a workaround [like this patch] for all customers who cannot do kernel hardening (OpenVZ) or those who don't want to pay for CL.

Thanks for your reply!

Karl

**Comment by HoustonDad** [comment]
Hi Karl,

I've forked off ea-apache2 and applied the hardening patch for 2.4. I've also sent this up to OBS to build the RPMs, and provide a yum repository as well. Would you mind letting me know your thoughts? I can make sure to keep this repo up to date if it's wanted.

Github fork: https://github.com/JPerkster/ea-apache2
OBS Project: https://build.opensuse.org/project/show/home:Jperkster:symlink_patch
OBS Yum Repo: http://download.opensuse.org/repositories/home:/Jperkster:/symlink_patch/

Hit up the Yum Repo link, pick your distro, and download the .repo file to your '/etc/yum.repos.d/' directory, and do a yum update. You should get an update from my repo. 

Also, if you need to downgrade, you can run set 'enabled=0' in the .repo file you downloaded and run: `yum downgrade ea-apache24 ea-apache24-tools ea-apache24-mod_headers ea-apache24-mod_proxy ea-apache24-mod_suexec ea-apache24-mod_proxy_http ea-apache24-mod_unique_id ea-apache24-mod_mpm_worker ea-apache24-mod_ssl ea-apache24-mod_proxy_fcgi ea-apache24-mod_cgid ea-apache24-mod_deflate ea-apache24-mod_expires ea-apr`

Let me know your thoughts. Thanks!

~~edit; I used the wrong patch in the above commits. I'm fixing this now.~~ 
Ok, I've updated with the full Symlink Protection Patch from EA3. I also had to patch APR, so that package will also be updated from this repo.

Note: This is the BlueHost patch, and it's going to cause noticeable performance degradation (around 10% loss in performance from httpd in my tests). Also, I'm doing this outside of cPanel, and this repo is not an official repo, but a personal one done by me on my off time. cPanel won't support this repo nor it's changes from cPanel's upstream repositories.

**Comment by karljohns0n** [comment]
Hi Jacob,

Thanks for the fork, I'll take a look at it. Yes it seems that the Bluehost patch cause more performance degradation then the Rack911 one so the second one should be preferred. Suggestion, wouldn't be more simple to add a new package (ie: ea-apache24-sympatch) that has "Provides: ea-apache24" so this way it could be supported by EA and we can use "yum swap ea-apache24 ea-apache24-sympatch) to swap from regular apache to the patched one? If the patched packages aren't in an official repo, I don't think customers will use it at all. 

With the conflict on modsec+ruid2 being removed soon and if the patched apache can't be in the official repo, we can close this issue.

Thanks!

Karl

**Comment by HoustonDad** [comment]
Hi Karl,

Thanks for the feedback! We're actively working on the conflict, and I hope to have it sent out in the next couple of weeks. We may do a small EA4 update tomorrow for PECL/PEAR fixes going to EDGE, however they unfortunately won't contain the fixes for Ruid2/ModSec.

I'd like to take the comments about my fork over to an issue there: https://github.com/JPerkster/ea-apache2-bluehost/issues/1

Thanks again for your feedback!
